//! Startup snippet generation for `koshell shell-init <shell>`.
//!
//! The snippet is installed as `eval "$(koshell shell-init zsh)"` at the top of
//! `~/.zshrc` (or `~/.bashrc`), and replaces the just-started interactive shell with a
//! koshell-wrapped one via `exec`. Keeping the snippet behind a subcommand means the
//! guard logic can evolve with koshell instead of being hard-coded into user rc files.
//!
//! Recursion is broken by the `KOSHELL=1` marker (`shell.rs`): the shell koshell spawns
//! re-sources the user's rc through the integration rc (`shell_integration.rs`), sees
//! the marker, and skips the `exec`. The remaining guards keep the snippet inert for
//! non-interactive shells, non-TTY stdio, and dumb terminals, and two escape hatches
//! (`KOSHELL_NO_AUTO=1`, or a `no-auto` file under the koshell config dir — creatable
//! without a working shell) ensure a broken koshell binary cannot lock the user out of
//! new terminals.

use clap::ValueEnum;

/// Shell dialects `shell-init` can emit a snippet for. Matches the shells that get
/// integration rc files in `shell_integration.rs`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum InitShell {
    Bash,
    Zsh,
}

/// Returns the startup snippet for `shell`, ready to be `eval`-ed by that shell.
pub fn snippet(shell: InitShell) -> &'static str {
    match shell {
        InitShell::Bash => BASH_SNIPPET,
        InitShell::Zsh => ZSH_SNIPPET,
    }
}

// The two snippets differ only in the interactivity test (`$-` has no `i` flag under
// zsh's default emulation; `[[ -o interactive ]]` is not valid bash). Both must stay
// `eval`-safe: no `exit`/`return` on the guard path, so a shell that fails the guard
// continues its rc unaffected.
const BASH_SNIPPET: &str = r#"# koshell auto-wrap (generated by `koshell shell-init bash`).
# Escape hatches: export KOSHELL_NO_AUTO=1, or create the file
# "${XDG_CONFIG_HOME:-$HOME/.config}/koshell/no-auto".
if [[ $- == *i* && -z "${KOSHELL-}" && -z "${KOSHELL_NO_AUTO-}" ]] &&
    [[ -t 0 && -t 1 && "${TERM-}" != dumb ]] &&
    [[ ! -e "${XDG_CONFIG_HOME:-$HOME/.config}/koshell/no-auto" ]] &&
    command -v koshell >/dev/null 2>&1; then
  exec koshell
fi
"#;

const ZSH_SNIPPET: &str = r#"# koshell auto-wrap (generated by `koshell shell-init zsh`).
# Escape hatches: export KOSHELL_NO_AUTO=1, or create the file
# "${XDG_CONFIG_HOME:-$HOME/.config}/koshell/no-auto".
if [[ -o interactive && -z "${KOSHELL-}" && -z "${KOSHELL_NO_AUTO-}" ]] &&
    [[ -t 0 && -t 1 && "${TERM-}" != dumb ]] &&
    [[ ! -e "${XDG_CONFIG_HOME:-$HOME/.config}/koshell/no-auto" ]] &&
    command -v koshell >/dev/null 2>&1; then
  exec koshell
fi
"#;

#[cfg(test)]
mod tests {
    use super::*;

    /// Syntax-checks `snippet` with `interpreter -n`; skips when the interpreter is
    /// not installed.
    fn assert_snippet_parses(candidates: &[&str], snippet: &str) {
        let Some(interpreter) = candidates.iter().find(|c| std::path::Path::new(c).exists()) else {
            eprintln!("skipping syntax check: none of {candidates:?} found");
            return;
        };
        let dir = tempfile::tempdir().expect("create temp dir");
        let file = dir.path().join("snippet");
        std::fs::write(&file, snippet).expect("write snippet");
        let status = std::process::Command::new(interpreter)
            .arg("-n")
            .arg(&file)
            .status()
            .expect("run syntax check");
        assert!(status.success(), "{interpreter} -n rejected the snippet");
    }

    #[test]
    fn bash_snippet_is_valid_bash() {
        assert_snippet_parses(
            &["/bin/bash", "/usr/bin/bash", "/opt/homebrew/bin/bash"],
            snippet(InitShell::Bash),
        );
    }

    #[test]
    fn zsh_snippet_is_valid_zsh() {
        assert_snippet_parses(
            &["/bin/zsh", "/usr/bin/zsh", "/opt/homebrew/bin/zsh"],
            snippet(InitShell::Zsh),
        );
    }

    #[test]
    fn snippets_carry_the_guards_and_the_exec() {
        for shell in [InitShell::Bash, InitShell::Zsh] {
            let text = snippet(shell);
            assert!(text.contains("${KOSHELL-}"), "nested-koshell guard");
            assert!(text.contains("${KOSHELL_NO_AUTO-}"), "env escape hatch");
            assert!(text.contains("koshell/no-auto"), "file escape hatch");
            assert!(text.contains("-t 0 && -t 1"), "TTY guard");
            assert!(text.contains("exec koshell"), "the exec itself");
            assert!(
                text.contains("command -v koshell"),
                "binary-existence guard"
            );
        }
    }
}
